name: Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  solana_version: 'v1.16.21'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  tests-general-1:
    name: Tests General 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hubbleprotocol/solana-setup-action@v0.2
        id: solana-setup
        with:
          solana-version: ${{ env.solana_version }}
          rust-shared-key: 'tests'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        # Add solana binaries to path - todo should not be needed
        run: |
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          yarn start-validator &
          npx ts-mocha tests/setup.test.ts --exit
          npx ts-mocha tests/flash_loan.test.ts --exit
          npx ts-mocha tests/liquidation*.test.ts --exit
          npx ts-mocha tests/pubkey_map.test.ts --exit

  tests-general-2:
    name: Tests General 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hubbleprotocol/solana-setup-action@v0.2
        id: solana-setup
        with:
          solana-version: ${{ env.solana_version }}
          rust-shared-key: 'tests'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        # Add solana binaries to path - todo should not be needed
        run: |
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          yarn start-validator &
          npx ts-mocha tests/market.test.ts --exit
          npx ts-mocha tests/obligation_types.test.ts --exit
          npx ts-mocha tests/obligation.test.ts --exit
          npx ts-mocha tests/referrals.test.ts --exit
          npx ts-mocha tests/reserve.test.ts --exit

  tests-leverage:
    name: Tests Leverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hubbleprotocol/solana-setup-action@v0.2
        id: solana-setup
        with:
          solana-version: ${{ env.solana_version }}
          rust-shared-key: 'tests'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        # Add solana binaries to path - todo should not be needed
        run: |
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          yarn start-validator &
          npx ts-mocha tests/leverage*.test.ts --parallel --exit

  tests-farms:
    name: Tests Farms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hubbleprotocol/solana-setup-action@v0.2
        id: solana-setup
        with:
          solana-version: ${{ env.solana_version }}
          rust-shared-key: 'tests'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        # Add solana binaries to path - todo should not be needed
        run: |
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          yarn start-validator &
          npx ts-mocha tests/farms_tests/**/*.test.ts --exit --parallel

  tests-repay-with-coll:
    name: Tests Repay with Collateral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hubbleprotocol/solana-setup-action@v0.2
        id: solana-setup
        with:
          solana-version: ${{ env.solana_version }}
          rust-shared-key: 'tests'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
      - uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        # Add solana binaries to path - todo should not be needed
        run: |
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          yarn start-validator &
          npx ts-mocha tests/repay_with_coll.test.ts --exit
